# Generated by Django 3.2.7 on 2021-12-04 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard', to=settings.AUTH_USER_MODEL),
        ),
    ]
