# Generated by Django 3.2.7 on 2021-12-16 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_app', '0002_auto_20211216_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 1, 51, 10, 990650, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 1, 51, 10, 991646, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 1, 51, 10, 990650, tzinfo=utc)),
        ),
    ]
