# Generated by Django 3.2.7 on 2021-12-25 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_app', '0003_auto_20211217_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 16, 22, 51, 574114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 16, 22, 51, 575019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 16, 22, 51, 574572, tzinfo=utc)),
        ),
    ]
