# Generated by Django 3.2.7 on 2021-12-25 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_app', '0004_auto_20211225_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 21, 13, 56, 737984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 21, 13, 56, 738983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 21, 13, 56, 737984, tzinfo=utc)),
        ),
    ]
