# Generated by Django 3.2.7 on 2021-12-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_app', '0004_auto_20211225_1622'),
        ('suggestion_app', '0005_auto_20211225_2113'),
    ]

    operations = [
    ]
