# Generated by Django 3.2.7 on 2021-12-28 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_app', '0006_merge_0004_auto_20211225_1622_0005_auto_20211225_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 21, 8, 47, 576903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 21, 8, 47, 578894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 21, 8, 47, 577898, tzinfo=utc)),
        ),
    ]
