# Generated by Django 3.2.7 on 2024-12-18 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_app', '0008_auto_20211229_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 6, 26, 14, 900505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 6, 26, 14, 901218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 6, 26, 14, 900833, tzinfo=utc)),
        ),
    ]
