# Generated by Django 3.2.7 on 2021-09-20 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('cf_handle', models.CharField(max_length=150)),
                ('university', models.CharField(blank=True, max_length=300, null=True)),
                ('submission_privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('PROTECTED', 'Protected')], default='PRIVATE', max_length=20)),
                ('mentor_list_privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('PROTECTED', 'Protected')], default='PRIVATE', max_length=20)),
                ('mentee_list_privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('PROTECTED', 'Protected')], default='PRIVATE', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_profile',
            },
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField()),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mentee', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('submission_privacy__in', ['PUBLIC', 'PRIVATE', 'PROTECTED'])), name='user_app_profile_submission_privacy_check_cons'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('mentor_list_privacy__in', ['PUBLIC', 'PRIVATE', 'PROTECTED'])), name='user_app_profile_mentor_list_privacy_check_cons'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('mentee_list_privacy__in', ['PUBLIC', 'PRIVATE', 'PROTECTED'])), name='user_app_profile_mentee_list_privacy_check_cons'),
        ),
    ]
