# Generated by Django 3.2.7 on 2021-12-16 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_app.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('cf_handle', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('university', models.CharField(blank=True, max_length=300, null=True)),
                ('timestamp_updatedsubmission', models.DateTimeField(default=datetime.datetime(2021, 12, 16, 18, 28, 7, 911699, tzinfo=utc))),
                ('is_updating', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_profile',
            },
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED_FROM_MENTOR', 'Requested from mentor'), ('REQUESTED_FROM_MENTEE', 'Requested from Mentee'), ('CURRENT', 'Current'), ('FORMER', 'Former')], default='FORMER', max_length=30)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_app_mentee',
            },
        ),
        migrations.AddConstraint(
            model_name='mentee',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['REQUESTED_FROM_MENTOR', 'REQUESTED_FROM_MENTEE', 'CURRENT', 'FORMER'])), name='user_app_mentee_status_check_cons'),
        ),
    ]
