# Generated by Django 3.2.7 on 2021-12-25 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp_updatedsubmission',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 16, 22, 51, 572399, tzinfo=utc)),
        ),
    ]
