# Generated by Django 3.2.7 on 2021-12-07 22:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp_updatedsubmission',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 4, 23, 44, 919223, tzinfo=utc)),
        ),
    ]
