# Generated by Django 3.2.7 on 2021-11-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userstatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorshipRequest',
        ),
    ]
