# Generated by Django 3.2.7 on 2021-12-08 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_profile_timestamp_updatedsubmission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='user_app_profile_mentor_list_privacy_check_cons',
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='user_app_profile_mentee_list_privacy_check_cons',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mentee_list_privacy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mentor_list_privacy',
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp_updatedsubmission',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 22, 12, 22, 435995, tzinfo=utc)),
        ),
    ]
