# Generated by Django 3.2.7 on 2021-12-28 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_profile_timestamp_updatedsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp_updatedsubmission',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 21, 8, 47, 574861, tzinfo=utc)),
        ),
    ]
