# Generated by Django 3.2.7 on 2021-12-09 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20211208_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee',
            old_name='user',
            new_name='mentor',
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp_updatedsubmission',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 12, 36, 57, 811211, tzinfo=utc)),
        ),
    ]
