# Generated by Django 3.2.7 on 2021-12-04 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0003_delete_mentorshiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='is_current',
        ),
        migrations.AddField(
            model_name='mentee',
            name='status',
            field=models.CharField(choices=[('REQUESTED_FROM_MENTOR', 'Requested from mentor'), ('REQUESTED_FROM_MENTEE', 'Requested from Mentee'), ('CURRENT', 'Current'), ('FORMER', 'Former')], default='FORMER', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mentee',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['REQUESTED_FROM_MENTOR', 'REQUESTED_FROM_MENTEE', 'CURRENT', 'FORMER'])), name='user_app_mentee_status_check_cons'),
        ),
        migrations.AlterModelTable(
            name='mentee',
            table='user_app_mentee',
        ),
    ]
