# Generated by Django 3.2.7 on 2021-12-09 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0004_auto_20211209_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp_updatedsubmission',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 12, 44, 38, 542770, tzinfo=utc)),
        ),
    ]
