# Generated by Django 3.2.7 on 2021-09-21 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('cf_problem_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newbie', models.IntegerField(default=0)),
                ('pupil', models.IntegerField(default=0)),
                ('specialist', models.IntegerField(default=0)),
                ('expert', models.IntegerField(default=0)),
                ('candidate_master', models.IntegerField(default=0)),
                ('master', models.IntegerField(default=0)),
                ('international_master', models.IntegerField(default=0)),
                ('grandmaster', models.IntegerField(default=0)),
                ('international_grandmaster', models.IntegerField(default=0)),
                ('legendary_grandmaster', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_app.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.ManyToManyField(to='problem_app.Tag'),
        ),
        migrations.CreateModel(
            name='AcceptedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_app.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
