# Generated by Django 3.2.7 on 2021-12-16 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problem_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedsubmission',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 18, 29, 5, 42563, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='timestamp_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 18, 29, 5, 41565, tzinfo=utc)),
        ),
    ]
