# Generated by Django 3.2.7 on 2021-11-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedsubmission',
            name='current_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProblemStatistic',
        ),
    ]
