# Generated by Django 3.2.7 on 2021-12-07 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problem_app', '0002_auto_20211207_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedsubmission',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 8, 14, 20, 342102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='timestamp_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 8, 14, 20, 341188, tzinfo=utc)),
        ),
    ]
