# Generated by Django 3.2.7 on 2021-12-07 22:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problem_app', '0002_auto_20211207_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptedsubmission',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='acceptedsubmission',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 4, 23, 44, 914225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='timestamp_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 4, 23, 44, 913229, tzinfo=utc)),
        ),
    ]
