# Generated by Django 3.2.7 on 2024-12-18 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problem_app', '0006_auto_20211229_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedsubmission',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 6, 26, 14, 894481, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='timestamp_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 6, 26, 14, 893750, tzinfo=utc)),
        ),
    ]
